apiVersion: v1
kind: Service
metadata:
  labels:
    name: haproxy
  name: haproxy-lb
  namespace: pacman
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: haproxy
  sessionAffinity: None
  type: LoadBalancer
