apiVersion: v1
kind: Service
metadata:
  namespace: mongo 
  name: mongo
spec:
  type: ClusterIP 
  ports:
    - protocol: TCP
      port: 27017 
      targetPort: 27017
      name: db
  selector:
    name: mongo
