apiVersion: v1
kind: Service
metadata:
  namespace: pacman
  name: pacman
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  selector:
    name: pacman 
