apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: pacman 
  name: haproxy
  labels:
    name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:  
      name: haproxy
  template:
    metadata:
      namespace: pacman
      labels:
        name: haproxy
    spec:
      containers:
      - name: haproxy
        image: registry.connect.redhat.com/haproxytech/haproxy:latest 
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/haproxy
          name: config
      volumes:
      - name: config
        configMap:
          name: 01-haproxy
