apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: pacman 
  name: pacman
  labels:
    name: pacman
spec:
  replicas: 1
  selector:
    matchLabels:  
      name: pacman
  template:
    metadata:
      namespace: pacman
      labels:
        name: pacman
    spec:
      containers:
      - name: pacman
        image: quay.io/ifont/pacman-nodejs-app:latest 
        env:
        - name: MONGO_SERVICE_HOST
        # Single member MongoDB
          value: internal-a4dfda3218e1e11e9967c0edf0f025f2-791543394.us-east-1.elb.amazonaws.com
        # Replicaset (federated) MongoDB
        #  value: mongo-east1.apps.east-1.sysdeseng.com,mongo-east2.apps.east-2.sysdeseng.com,mongo-west2.apps.west-2.sysdeseng.com
        # Comment out MONGO_REPLICA_SET for the single-member Mongo
        # - name: MONGO_REPLICA_SET
        #  value: rs0
        - name: MONGO_AUTH_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mongodb-users-secret
        - name: MONGO_AUTH_PWD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mongodb-users-secret
        - name: MONGO_DATABASE
          value: pacman
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USE_SSL
          value: "false"
        - name: MONGO_VALIDATE_SSL
          value: "false"
        ports:
        - containerPort: 8080 
