apiVersion: v1
kind: Secret
metadata:
  namespace: pacman
  name: mongodb-users-secret
type: Opaque 
data: 
  # clyde
  database-admin-password: Y2x5ZGU=
  # pacman
  database-name: cGFjbWFu
  # pinky
  database-password: cGlua3k=
  # blinky
  database-user: Ymxpbmt5
